### ISSUE TITLE
Manage time zone information for events

### ISSUE THREAD

**Issue by uklotzde** [kartevonmorgen/openfairdb#139]
Currently the applicable time zone of an event is resolved by the client:
https://github.com/flosse/kartevonmorgen/issues/506

In the future this information should be managed by the server. If no explicit time zone information is provided then the server should deduce the applicable time zone from the geographical location (if available) of the event.

**Comment by uklotzde** [comment]
https://codeblog.jonskeet.uk/2019/03/27/storing-utc-is-not-a-silver-bullet/
http://www.creativedeletion.com/2015/03/19/persisting_future_datetimes.html

**Comment by uklotzde** [comment]
Bulletproof solution for future events
* Wall time (NaiveDateTime?) of the instant
* Local time zone
* UTC offset of the local time zone at the instant (as known when scheduling the event, only used as a tie breaker)

**Comment by uklotzde** [comment]
Date and time of events is stored as a naive date/time without any time zone information, i.e. the time zone is implicit and depends on the geographical location of the event.

**Comment by wellemut** [comment]
# Problem
Time shown on an entry is one hour earlier than what you see when you edit it.
## Time in Entry-Detail:
![image](https://user-images.githubusercontent.com/15019030/72652351-ba2af600-3986-11ea-8480-932c12f48cbe.png)

## Time while editing:
![image](https://user-images.githubusercontent.com/15019030/72652371-cca52f80-3986-11ea-87c8-235e1d2ee039.png)

Check it out on this event: https://kartevonmorgen.org/#/?entry=78dec0b7aca046d3b18945ae1672e203&zoom=15.00&categories=event

@regenduft What is wrong?
This is probably a frontend issue, because the backend would not change the time just for fun?

**Comment by regenduft** [comment]
this issue has been resolved BEFORE deployment to www.kartevonmorgen.org - when deploying to www.kartevonmorgen.org, I did NOT deploy to mobile.kartevonmorgen.org, so this issue may still be visible there, also its possible that miguel did not yet merge the newest updates in his code for beta.kartevonmorgen.org

https://www.kartevonmorgen.org however does not have this issue.

But you RE-USED some issue about another topic from feburary 2019, so I am not closing it, is this correct, wellemut?

**Comment by regenduft** [comment]
issue also not present on mobile.kartevonmorgen.org - I don't know where you found it yesterday.

**Comment by wellemut** [comment]
Ok, really strange. It just happens here on this entry. https://kartevonmorgen.org/#/?entry=78dec0b7aca046d3b18945ae1672e203&zoom=15.00&categories=event
All the others are correct.
And on this as well: https://kartevonmorgen.org/#/?entry=72fc075d86694e1799d13ac152295757&zoom=17.00&categories=event,initiative,company

So: only on entry which I entere, the time shown in the event is one hour earlier, than what I put in.
Lets see if somebody else reports a similar thing.

**Comment by regenduft** [comment]
wow, you're right!

The issue happens with all entries, that start in future, after summer time has started.

So this is indead an issue I need to fix somehow.

the reason for this is, that the date - time - picker CANNOT be set to use UTC - it is simply not supported.

so the only solution was, to initialize the time picker with "time of event - difference of computer time and UTC"

however I will need to initialize the time picker with "time of event - (difference of time, your computer will display at the time of the event  and UTC)"

**Comment by regenduft** [comment]
helmut, are you able to re-open the issue? I can't

**Comment by uklotzde** [comment]
The backend just stores what it receives from the client, without applying any time zone conversions. Please report if you find issues or how we could improve the situation.

Modifying the representation in the backend would involve breaking changes for all existing clients that are difficult to coordinate.

**Comment by uklotzde** [comment]
Conversions:

```
event.start = Date.UTC(year, month_index, day, hours, minutes, seconds) / 1000
```

```
start_date = new Date(event.start * 1000);
year = start_date.getUTCFullYear();
month_index = start_date.getUTCMonth(); // 0 = Jan, 11 = Dec
day = start_date.getUTCDay();
hours = start_date.getUTCHours();
minutes = start_date.getUTCMinutes();
seconds = start_date.getUTCSeconds();
```

Not tested, just looked up: https://developer.mozilla.org/de/docs/Web/JavaScript/Reference/Global_Objects/Date/UTC

**Comment by regenduft** [comment]
hi uwe, thanks thats nice.

the date picker takes seconds since 1/1/1970 utc and displays them as a local time of the user agent, no way to configure him to do something else.

so to trick the date picker I am "adding" the timeZoneOffset (which is negative in Berlin) of the user agent to these seconds since 1/1/1970 utc: (event.start + (new window.Date().getTimezoneOffset() * 60)) * 1000 

this is actually "tricking" the date picker because I am giving him a less seconds than utc - but because the date picker thinks i do NOT want to see utc, he will "substract" the (negative) timeZoneOffset again to display local time to the user and because I "added" the (negative) offset before, he will actually display utc.

my only failure was to write new window.Date() instead of writing (new window.Date(event.start * 1000) to get the timezoneOffset of the time of the event, which may be different to the current timezoneOffset

probably this will still fail at the exact date of summertime switching but I think we can life with that.

**Comment by uklotzde** [comment]
If the date picker only supports the local time of the user agent then we have to compensate for this time zone transformation. Add the local time zone offset when setting the initial time of the date picker and subtract the local time zone offset when reading the selected time.

**Comment by uklotzde** [comment]
I agree that we can ignore the edge cases.

**Comment by regenduft** [comment]
fixed with https://github.com/kartevonmorgen/kartevonmorgen/commit/5838120de0951590cec89b351c1161fdd0c3c03d
