### ISSUE TITLE
Differentiate Comments from Ratings

### ISSUE THREAD

**Issue by miguelsan** [kartevonmorgen/openfairdb#245]
The [last implemented feature of KVM](https://github.com/kartevonmorgen/kartevonmorgen/issues/515) allows adding a comment on an already rated aspect of an entry. But currently there is no way to differentiate between further normal ratings and comments to a given rating, since they are all the same, and the UI can only show all subsequent siblings as comments, which does not reflect the expected functionality.

Please add a new path in the API which returns an timely ordered list of the comments to a rating.
In order to reduce requests, it could be wise to also allow returning ratings and comments of an entry at once. Afterwards the UI can reflect this properly.

This could be implemented as a new `Comment` model, or simply as an added `parent` field to a Rating, where 0 or null value would represent "I am not a comment".

**Comment by wellemut** [comment]
@uklotzde 
Is this clear enough / seems a good way for you?
than please add this field /api

👍

**Comment by miguelsan** [comment]
A new requirement has arised:
The comment requires just one content field: description. Source and title are allowed.

**Comment by miguelsan** [comment]
After further analysis, I realized that the request was incomplete and therefore almost nonsense, since it forgot to mention the writes.

Closing this in favor of #246.

**Comment by wellemut** [comment]
# Aktueller Vorschlag:
## Term-Definition (Datastructure)
- **Rating**: A new rating (what we have today) has the following fields
{
  "id": **"7cee99c287094a94acbdcf29ffff2e80",**
  "title": "string",
  "created": 0,
  "value": 0,
  "context": "string",
   **"parentrating": "0"** (Die oberste Bewertung hat dieses Feld gar nicht, oder der Wert ist 0)
  "source": "string",
  "comments": [
    {
      "id": "7cee99c287094a94acbdcf29ffff2e85",
      "created": 1547403509000,
      "text": "string"
    }
  ]
}
- **Answer**: response-rating (What Migel developed in https://github.com/kartevonmorgen/kartevonmorgen/issues/515) to an existing rating has the follwing fields
{
  "id": "7cee99c287094a94acbdcf29ffff2e85",
  "title": "string",
  "created": 0,
  "value": 0,
  ~~"context": "string",~~ (The user can not choose a different category than the parent rating, therefor this field is empty or the frontend just copies the value from the parent rating. 
  **"parentrating": "ID" (hier speichert das Frontend die Bewertungs-ID ab, auf die sich diese Antwort bezieht. Es kann aber auch die Antwort-Id abspeichern, von der letzten antwort, auf die es sich bezieht, wenn die Antwort-ID logisch gewählt ist)**
  "source": "string",
  "comments": [
    {
      "id": "7cee99c287094a94acbdcf29ffff2e85",
      "created": 1547403509000,
      "text": "string"
    }
  ]
}

## Fontenend-Interpretation:
The Frontend
1.  Loads all ratings 
2.  sorts the ratings by category
3.  sorts the ratings cronologically within the categories (newest on the top)
4.  Einrücken: All ratings, that has a parent-ID are subgrouped to that rating and sorted chronologically.

### What happens, if the Parent gets deleted?
-> The frontend should give logical IDs for Answer. 
i.e.:
Parent-ID: 7cee99c287094a94acbdcf29ffff2e80
Child-ID1: 7cee99c287094a94acbdcf29ffff2e80+XXX001
Child-ID2: 7cee99c287094a94acbdcf29ffff2e80+XXX001+YYY001
XXX and YYY= a random string-combination.

So even when the Parent-Rating is deleted, the others know, that they belong together...

# Proposal with fundamental changes:
We could clean it up and make it strait, but than kartevonmorgen.org and openfairDB.org would have to change their interfaces, which would cost more than we have right know.

- Rating has the following fields, and the Answerres are integrated.
{
  "id": **"7cee99c287094a94acbdcf29ffff2e80",** (Rating ID)

  "created": 0,

  "context": "string",


  "comments1": [
    {
      "id": "7cee99c287094a94acbdcf29ffff2e85",
      "title": "string",
      "created": 1547403509000,
      "text": "string"
      "value": 0,
      "source": "string",
    }
  ]

  "comments2": [
    {
      "id": "7cee99c287094a94acbdcf29ffff2e85",
      "title": "string",
      "created": 1547403509000,
      "text": "string"
      "value": 0,
      "source": "string",
    }
  ]

  "commentsXX": [
    {
      "id": "7cee99c287094a94acbdcf29ffff2e85",
      "title": "string",
      "created": 1547403509000,
      "text": "string"
      "value": 0,
      "source": "string",
    }
  ]
}

### What happens if the parent gets deleted
Well, no problem, comment1 ist just missing, but comment2 will get shown as it would be a parent rating, and comment3 will be the first child.

**Comment by wellemut** [comment]
This is what we (@flosse and @wellemut) are looking for:

Instead of having **one rating** with multiple comments, we have **one topic** with multiple rated comments:

```json
{
  "id": "7cee99c287094a94acbdcf29ffff2e85",
  "topic": "string",
  "created": 1547403509000,
  "context": "string",
  "ratings": [
    {
      "id": "edfre99c287094a94acbdcf29ffffaklsdufz",
      "created": 1547403509000,
      "comment": "string",
      "value": 0,
      "source": "string",
    }
  ]
}
```

@uklotzde what do you think?
![grafik](https://user-images.githubusercontent.com/15019030/75837471-3b1e3f80-5dc5-11ea-955b-f089821e3899.png)

**Comment by uklotzde** [comment]
Migration:
- Rating -> Topic + Comment with rating value
- Comment -> Comment with value 0

**Comment by flosse** [comment]
Here is another approach:

All ratings that have the exact same `title` will be grouped by the frontend. And the ordering is easy because of the timestamp :)

Here is how it could be done (untested, primitive draft):
```javascript
const topics = entry.ratings
                    .map(r => r.title) // just look at the titles
                    .filter((el,idx,self) => idx == self.indexOf(el)); // remove duplicates

const groups = topics.map(t => entry.ratings.filter(r => r.title == t)).filter(g => g.length > 0);

const dom_elements = groups.map(r =>
    <div class="group">
      <h3>{r[0].title}</h3>
      <ul>
       {r[1..].map(r => <li>{ /*..*/ }</li>)}
      </ul>
    </div>);
```
