### ISSUE TITLE
Check for duplicate entries payload

### ISSUE THREAD

**Issue by iJoise** [kartevonmorgen/openfairdb#373]
I ran the tests of the changes described here https://github.com/kartevonmorgen/openfairdb/issues/363 and ran into the problem that we also have to make additional changes to send the payload. When we discussed this at the hackathon, we were trying to send data from forms without additional transformations on the client. I will show in the screenshots the option that works now.
<img width="526" alt="lic" src="https://user-images.githubusercontent.com/74713958/128993286-b972cbe9-5a60-4be5-b198-465cbfdb83c0.png">

**Comment by uklotzde** [comment]
In the API `license` is consistently defined and documented as a simple string and not an array. Passing an empty string should work as demonstrated in #363. v0.10.5 will soon allow to omit these unused properties for /search/duplicates.

The wrong array type in the client cannot be caused by ofdb according to the code.

**Comment by uklotzde** [comment]
I have updated the minimum payload for v0.10.4 in #363.

POST https://kartevonmorgen.org/api/v0/search/duplicates
```json
{
"title": "test",
"description": "test test test",
"lat": 42.750541777589376,
"lng": 10.152115243848346,
"license": "",
"tags": [],
"categories": []
}
```
